apiVersion: v1
kind: Pod
metadata:
  name: {{ template "cp-ksql-server.fullname" . }}
  labels:
    app: {{ template "cp-ksql-server.name" . }}
    chart: {{ template "cp-ksql-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.affinity.enabled }}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        {{- range .Values.affinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms }}
        - matchExpressions:
          {{- range .matchExpressions }}
          - key: {{ .key | quote }}
            operator: {{ .operator }}
            values: 
            {{- range .values }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
  {{- end }}
